version: '3.0'
services:
  openconnect:
    build: .
    restart: always
    container_name: ocserv
    privileged: true
    hostname: oc.ishadow.me
    ports:
      - 443:443/udp
      - 443:443
    environment:
      - CA_CN=VPN CA
      - CA_ORG=Big Corp
      - CA_DAYS=9999
      - SRV_CN=oc.ishadow.me
      - SRV_ORG=My Company
      - SRV_DAYS=9999
